"""
Base Strategy

Abstract base class for all trading strategies.
"""

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional, List, Dict, Any
import uuid

logger = logging.getLogger(__name__)


class SignalType(Enum):
    """Signal type enumeration."""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    CLOSE = "close"


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    symbol: str
    signal_type: SignalType
    strength: float = 1.0  # 0 to 1, indicates confidence
    quantity: Optional[float] = None
    limit_price: Optional[float] = None
    stop_price: Optional[float] = None
    strategy_id: str = ""
    signal_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Convert signal to dictionary."""
        return {
            "signal_id": self.signal_id,
            "symbol": self.symbol,
            "signal_type": self.signal_type.value,
            "strength": self.strength,
            "quantity": self.quantity,
            "limit_price": self.limit_price,
            "stop_price": self.stop_price,
            "strategy_id": self.strategy_id,
            "timestamp": self.timestamp.isoformat(),
            "metadata": self.metadata,
        }


class BaseStrategy(ABC):
    """
    Abstract base class for trading strategies.

    Provides common interface for:
    - Strategy initialization and configuration
    - Signal generation
    - Position management
    - Performance tracking
    """

    def __init__(self, strategy_id: str, config: Optional[Dict[str, Any]] = None):
        """
        Initialize strategy.

        Args:
            strategy_id: Unique identifier for the strategy
            config: Strategy configuration parameters
        """
        self.strategy_id = strategy_id
        self.config = config or {}
        self.enabled = self.config.get("enabled", True)
        self._signals: List[Signal] = []
        self._positions: Dict[str, float] = {}
        self._last_run: Optional[datetime] = None
        self._run_count = 0
        self._performance: Dict[str, float] = {
            "total_signals": 0,
            "buy_signals": 0,
            "sell_signals": 0,
            "pnl": 0.0,
        }

    @property
    @abstractmethod
    def name(self) -> str:
        """Strategy name."""
        pass

    @property
    @abstractmethod
    def description(self) -> str:
        """Strategy description."""
        pass

    @abstractmethod
    def on_data(self, data: Dict[str, Any]) -> List[Signal]:
        """
        Process new data and generate signals.

        This is the main strategy logic method.

        Args:
            data: Market data dictionary

        Returns:
            List of trading signals
        """
        pass

    def run(self, data: Dict[str, Any]) -> List[Signal]:
        """
        Execute strategy with provided data.

        Args:
            data: Market data dictionary

        Returns:
            List of trading signals
        """
        if not self.enabled:
            logger.debug(f"Strategy {self.name} is disabled")
            return []

        try:
            signals = self.on_data(data)

            # Tag signals with strategy ID
            for signal in signals:
                signal.strategy_id = self.strategy_id

            # Track signals
            self._signals.extend(signals)
            self._update_performance(signals)
            self._last_run = datetime.now()
            self._run_count += 1

            if signals:
                logger.info(f"Strategy {self.name} generated {len(signals)} signals")

            return signals

        except Exception as e:
            logger.error(f"Strategy {self.name} error: {e}")
            return []

    def _update_performance(self, signals: List[Signal]):
        """Update performance metrics."""
        self._performance["total_signals"] += len(signals)
        for signal in signals:
            if signal.signal_type == SignalType.BUY:
                self._performance["buy_signals"] += 1
            elif signal.signal_type == SignalType.SELL:
                self._performance["sell_signals"] += 1

    def update_position(self, symbol: str, quantity: float):
        """Update tracked position for a symbol."""
        self._positions[symbol] = quantity
        if quantity == 0:
            del self._positions[symbol]

    def get_position(self, symbol: str) -> float:
        """Get current position for a symbol."""
        return self._positions.get(symbol, 0)

    def get_all_positions(self) -> Dict[str, float]:
        """Get all positions."""
        return self._positions.copy()

    def update_pnl(self, pnl: float):
        """Update strategy PnL."""
        self._performance["pnl"] += pnl

    def get_signals(self, limit: int = 100) -> List[Signal]:
        """Get recent signals."""
        return self._signals[-limit:]

    def get_performance(self) -> Dict[str, Any]:
        """Get strategy performance metrics."""
        return {
            **self._performance,
            "run_count": self._run_count,
            "last_run": self._last_run.isoformat() if self._last_run else None,
            "positions": len(self._positions),
        }

    def get_status(self) -> Dict[str, Any]:
        """Get strategy status."""
        return {
            "strategy_id": self.strategy_id,
            "name": self.name,
            "enabled": self.enabled,
            "run_count": self._run_count,
            "last_run": self._last_run.isoformat() if self._last_run else None,
            "total_signals": self._performance["total_signals"],
        }

    def enable(self):
        """Enable the strategy."""
        self.enabled = True
        logger.info(f"Strategy {self.name} enabled")

    def disable(self):
        """Disable the strategy."""
        self.enabled = False
        logger.info(f"Strategy {self.name} disabled")

    def reset(self):
        """Reset strategy state."""
        self._signals.clear()
        self._positions.clear()
        self._last_run = None
        self._run_count = 0
        self._performance = {
            "total_signals": 0,
            "buy_signals": 0,
            "sell_signals": 0,
            "pnl": 0.0,
        }
        logger.info(f"Strategy {self.name} reset")
